### ISSUE TITLE
Expose attr-value types and how to cite in /xref

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec-web-services#186]
For example, `<link rel=manifest>` is exported from html, and should be citable as `[^link/rel/manifest^]`. 

Similarly, we want:

```
[^html-global/role/button^]
```

**Comment by sidvishnoi** [comment]
This works already: https://respec.org/xref/?term=text&specs=html&types=attr-value, but the terms aren't in webref (yet?).

**Comment by marcoscaceres** [comment]
Weird... I was expecting to see https://respec.org/xref/?term=manifest there as a attribute value for a `<link rel=>`

**Comment by marcoscaceres** [comment]
Ok, yeah... they didn't get exported from HTML.
