### ISSUE TITLE
xref: Some page visibility entries not showing up

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec-web-services#202]
The following entry for "external now visible algorithm" is not showing up in xref for some reason: 

https://github.com/w3c/webref/blob/cd238a8986d9c1355ff200e29db21f896c72d43f/tr/dfns/page-visibility-2.json#L228-L244

**Comment by sidvishnoi** [comment]
They both have `type: "abstract-op"`, we only support `dfn`. From Bikeshed:
> 
> abstract-op (for "English-language algorithms")
> dfn (for general terms and phrases, and a catch-all for anything else)

How do you suggest going forward? Rename abstract-op to dfn in ReSpec data, or add a new supported search type (with potentially new syntax?)?

**Comment by marcoscaceres** [comment]
> How do you suggest going forward? Rename abstract-op to dfn in ReSpec data, or add a new supported search type (with potentially new syntax?)?

I don't think we need a new syntax. We should treat them as dfn and link to them with [=the whatever algo=] (same as BS).
