### ISSUE TITLE
When I update my github issues (label for example) they are not updated in the respec, even if I reload the page

### ISSUE THREAD

**Issue by sabinem** [w3c/respec-web-services#212]
## Important info

- URL to affected spec: https://dcat-ap-ch-def.clients.liip.ch/releases/2.0/dcat-ap-ch.html
- ReSpec version: 26.8.14
- github repo: https://github.com/opendata-swiss/dcat_ap_ch
- 
### Problem:
My issue paragraphs pull in old labels and text instead of the updated labels and content, when I update my issues on github, see here  https://dcat-ap-ch-def.clients.liip.ch/releases/2.0/dcat-ap-ch.html#issue-summary
Issue Nr,19 gets the wrong label. Can that be changed?

**Comment by marcoscaceres** [comment]
Ok, PR sent https://github.com/w3c/respec-web-services/pull/213
